from setuptools import setup, find_packages

setup(
    name="nlp-hub",
    version="1.0.0",
    description="A comprehensive NLP toolkit and learning hub",
    author="NLP-Hub Contributors",
    packages=find_packages(),
    install_requires=[
        "nltk>=3.8",
        "spacy>=3.6.0",
        "transformers>=4.30.0",
        "torch>=2.0.0",
        "scikit-learn>=1.3.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.15.0",
        "wordcloud>=1.9.0",
        "jupyter>=1.0.0",
        "gensim>=4.3.0",
        "textblob>=0.17.0",
        "vaderSentiment>=3.3.2",
        "flask>=2.3.0",
        "streamlit>=1.25.0",
        "beautifulsoup4>=4.12.0",
        "requests>=2.31.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)